name: ml-ens-docking
channels:
  - defaults
dependencies:
  - scikit-learn
  - rpy2
  - seaborn
  - pandas
  - python=3.7
  - jupyter
  - orange3
  - mlxtend
  - rdkit
  - bokeh
  - plotly
  - jupyterlab
  - r-base=4.0.3
  - conda-forge::ncurses
  - plip
  - oddt
  - beautifulsoup4
  - modeller
  - ambertools
  - pdb2pqr
  - nodejs
  - rise
  - jupyterlab-git
  - autogrid
  - plotly-orca
